// mng/app/portal/(auth)/tickets/page.tsx
import { getPortalSession } from "@/lib/portal-auth";
import { query } from "@/lib/db";
import { redirect } from "next/navigation";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Talepler" };

export default async function PortalTicketsPage() {
  const session = (await getPortalSession())!;
  const { permissions, customer_id, email } = session;

  if (!permissions.tickets) redirect("/portal/dashboard");

  const tickets = permissions.own_only && permissions.tickets
    ? await query<{
        id: number; subject: string; status: string; priority: string;
        created_at: string; updated_at: string; from_email: string;
      }>(
        `SELECT id,subject,status,priority,created_at,updated_at,from_email
         FROM tickets WHERE customer_id=$1 AND LOWER(from_email)=LOWER($2)
         ORDER BY created_at DESC`,
        [customer_id, email]
      )
    : await query<{
        id: number; subject: string; status: string; priority: string;
        created_at: string; updated_at: string; from_email: string;
      }>(
        `SELECT id,subject,status,priority,created_at,updated_at,from_email
         FROM tickets WHERE customer_id=$1
         ORDER BY created_at DESC`,
        [customer_id]
      );

  const STATUS_LABEL: Record<string, string> = {
    open: "Açık", in_progress: "İşlemde", waiting: "Bekliyor",
    resolved: "Çözüldü", closed: "Kapatıldı",
  };
  const STATUS_COLOR: Record<string, string> = {
    open: "#3b82f6", in_progress: "#f59e0b", waiting: "#8b5cf6",
    resolved: "#22c55e", closed: "#94a3b8",
  };
  const PRIORITY_LABEL: Record<string, string> = {
    low: "Düşük", normal: "Normal", high: "Yüksek", critical: "Kritik",
  };
  const PRIORITY_COLOR: Record<string, string> = {
    low: "#64748b", normal: "#3b82f6", high: "#f59e0b", critical: "#ef4444",
  };

  const openCount = tickets.filter((t) => !["closed", "resolved"].includes(t.status)).length;

  return (
    <>
      <style>{css}</style>
      <div className="page-head">
        <h1 className="page-title">Talepler</h1>
        <span className="count-badge">{tickets.length} toplam</span>
        {openCount > 0 && <span className="open-badge">{openCount} açık</span>}
      </div>

      {tickets.length === 0 ? (
        <div className="empty">Henüz destek talebi bulunmuyor.</div>
      ) : (
        <div className="table-wrap">
          <table className="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Konu</th>
                {!permissions.own_only && <th>Gönderen</th>}
                <th>Durum</th>
                <th>Öncelik</th>
                <th>Tarih</th>
                <th>Son Güncelleme</th>
              </tr>
            </thead>
            <tbody>
              {tickets.map((t) => (
                <tr key={t.id}>
                  <td className="id-col">#{t.id}</td>
                  <td className="subject-col">{t.subject}</td>
                  {!permissions.own_only && (
                    <td className="dim">{t.from_email}</td>
                  )}
                  <td>
                    <span className="chip" style={{ color: STATUS_COLOR[t.status] ?? "#64748b", background: (STATUS_COLOR[t.status] ?? "#64748b") + "18" }}>
                      {STATUS_LABEL[t.status] ?? t.status}
                    </span>
                  </td>
                  <td>
                    <span className="chip" style={{ color: PRIORITY_COLOR[t.priority] ?? "#64748b", background: (PRIORITY_COLOR[t.priority] ?? "#64748b") + "18" }}>
                      {PRIORITY_LABEL[t.priority] ?? t.priority}
                    </span>
                  </td>
                  <td className="dim date-col">{new Date(t.created_at).toLocaleDateString("tr-TR")}</td>
                  <td className="dim date-col">{new Date(t.updated_at).toLocaleDateString("tr-TR")}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}

const css = `
.page-head{display:flex;align-items:center;gap:10px;margin-bottom:20px;flex-wrap:wrap}
.page-title{font-size:20px;font-weight:800;color:#0f172a;margin:0;letter-spacing:-0.3px}
.count-badge{font-size:12px;font-weight:700;color:#64748b;background:#e2e8f0;border-radius:6px;padding:3px 8px}
.open-badge{font-size:12px;font-weight:700;color:#3b82f6;background:rgba(59,130,246,0.1);border-radius:6px;padding:3px 8px}
.empty{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:40px;text-align:center;color:#64748b;font-size:14px}
.table-wrap{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;overflow-x:auto}
.table{width:100%;border-collapse:collapse;min-width:540px}
.table th{padding:11px 14px;text-align:left;font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;border-bottom:1px solid #f1f5f9;white-space:nowrap}
.table td{padding:13px 14px;border-bottom:1px solid #f8fafc;font-size:13px;color:#1e293b;vertical-align:middle}
.table tr:last-child td{border-bottom:none}
.table tr:hover td{background:#fafafa}
.id-col{font-family:monospace;font-size:12px;color:#94a3b8;font-weight:700}
.subject-col{font-weight:600;max-width:260px}
.dim{color:#64748b;font-size:12px}
.date-col{white-space:nowrap}
.chip{font-size:10px;font-weight:700;padding:3px 8px;border-radius:5px;white-space:nowrap}
`;

// gox/panel/src/routes/owner/tickets/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData, ActionData } from './$types';
	let { data, form }: { data: PageData; form: ActionData } = $props();
	let adding = $state(false);
</script>

<svelte:head><title>Destek · goX Platform</title></svelte:head>

<section class="head">
	<div><p class="eyebrow">Ticket yönetimi</p><h1>Destek</h1></div>
	<button class="btn btn--accent" onclick={() => (adding = !adding)} disabled={data.tenants.length === 0}>{adding ? 'Kapat' : '+ Yeni ticket'}</button>
</section>

{#if form?.error}<p class="err">{form.error}</p>{/if}

{#if adding}
	<form class="card add" method="POST" action="?/create" use:enhance={() => async ({ update }) => { await update(); adding = false; }}>
		<div class="grid">
			<label class="field"><span>Tenant</span>
				<select class="input" name="customer_id" required>{#each data.tenants as t}<option value={t.id}>{t.name}</option>{/each}</select></label>
			<label class="field"><span>Öncelik</span>
				<select class="input" name="priority"><option value="normal">Normal</option><option value="high">Yüksek</option><option value="low">Düşük</option></select></label>
		</div>
		<label class="field"><span>Konu</span><input class="input" name="subject" required /></label>
		<label class="field"><span>İlk mesaj</span><textarea class="input" name="body" rows="3"></textarea></label>
		<button class="btn btn--accent" type="submit">Ticket aç</button>
	</form>
{/if}

<section class="card list">
	<table class="tbl">
		<thead><tr><th>Konu</th><th>Tenant</th><th>Öncelik</th><th>Mesaj</th><th>Güncelleme</th><th>Durum</th></tr></thead>
		<tbody>
			{#each data.tickets as t (t.id)}
				<tr onclick={() => (window.location.href = `/owner/tickets/${t.id}`)} class="clickable">
					<td class="name">{t.subject}</td>
					<td>{t.customer}</td>
					<td class="up">{t.priority}</td>
					<td class="mono">{t.messages}</td>
					<td class="mono">{t.updated}</td>
					<td><span class="tag {t.status === 'open' ? 'tag--live' : 'tag--off'}">{t.status === 'open' ? 'Açık' : 'Kapalı'}</span></td>
				</tr>
			{/each}
			{#if data.tickets.length === 0}<tr><td colspan="6" class="empty">Ticket yok.</td></tr>{/if}
		</tbody>
	</table>
</section>

<style>
	.head { display: flex; align-items: flex-end; justify-content: space-between; gap: 1rem; margin-bottom: 1.6rem; }
	.head h1 { font-size: 2rem; margin: 0.4rem 0 0; }
	.err { background: color-mix(in srgb, var(--danger) 14%, var(--card)); border: 1.4px solid var(--danger); color: var(--danger); padding: 0.6rem 0.9rem; border-radius: var(--radius); margin-bottom: 1rem; }
	.add { padding: 1.5rem; margin-bottom: 1.2rem; }
	.add .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
	.add textarea { font-family: var(--font-text); resize: vertical; }
	.list { padding: 0.4rem 1.4rem 0.8rem; }
	.tbl { width: 100%; border-collapse: collapse; }
	.tbl th { text-align: left; font-family: var(--font-mono); font-size: 0.62rem; letter-spacing: 0.1em; text-transform: uppercase; color: var(--ink-soft); padding: 0.9rem 0 0.6rem; border-bottom: 1.5px solid var(--line); }
	.tbl td { padding: 0.8rem 0; border-bottom: 1px solid color-mix(in srgb, var(--line) 18%, transparent); font-size: 0.92rem; }
	.tbl tr:last-child td { border-bottom: none; }
	.clickable { cursor: pointer; }
	.clickable:hover td { background: var(--paper-2); }
	.name { font-family: var(--font-display); font-weight: 600; }
	.up { font-family: var(--font-mono); font-size: 0.74rem; text-transform: uppercase; }
	.mono { font-family: var(--font-mono); }
	.empty { text-align: center; color: var(--ink-soft); padding: 1.6rem 0; }
</style>
